# Generated by Django 4.0.5 on 2022-06-22 13:03

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('house_type', models.CharField(choices=[('Apartment', 'Apartment.'), ('Condo', 'Condo.'), ('Bungalow', 'Bungalow.')], max_length=20)),
                ('units', models.IntegerField()),
                ('kitchen', models.IntegerField(max_length=2)),
                ('parking', models.IntegerField(max_length=2)),
                ('house_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='house_image')),
                ('house_location', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='hunter.location')),
            ],
        ),
    ]
