# Generated by Django 4.0.5 on 2022-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='kitchen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='parking',
            field=models.IntegerField(),
        ),
    ]
