# Generated by Django 4.0.5 on 2022-06-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0002_alter_house_kitchen_alter_house_parking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='house',
            name='house_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
